apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap
data:
  config.py: |
    test_string = "this is a test string"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: python-test
      image: python:latest
      stdin: true
      volumeMounts:
        - name: conf-vol
          mountPath: /etc/config
  volumes:
    - name: conf-vol
      configMap:
        name: test-configmap